### ISSUE TITLE
force_panelsizes and ggMarginal

### ISSUE THREAD

**Issue by robinweide** [teunbrand/ggh4x#119]
Again, thanks so much for this excellent package.

**Background**
I want to create a fixed-size scatterplot, which includes density plots as marginals. 
Without the fixed-size, this is my reprex:

```
p <- ggplot(mtcars, aes(x = mpg, y = disp)) +
  geom_point()
p <- ggMarginal(p)
grid::grid.newpage()
grid::grid.draw(p)
```
![image](https://github.com/teunbrand/ggh4x/assets/7115143/84e27539-d67c-4a88-9190-b87abbce90de)

**Issue**
When I add `force_panelsizes`, it does a great job on the main panel. However, the marginals take over te rest of the available canvas.

```
p <- ggplot(mtcars, aes(x = mpg, y = disp)) +
  geom_point() +
  force_panelsizes(
    total_width = unit(42, "mm"),
    total_height = unit(42, "mm")
  )
p <- ggMarginal(p)
grid::grid.newpage()
grid::grid.draw(p)
```
![image](https://github.com/teunbrand/ggh4x/assets/7115143/7eeb9775-6f74-4d97-9b9f-4cd178e2585b)

**Proposed solution**
I expect this is more of an issue of the `ggExtra` package, but I was hoping for a workaround within `ggh4x` nonetheless. A workaround I have been using is tweaking the chunk parameters `fig.height` and `fig.width`, but that forces all plots in the same chunk to abide by those dimensions. Preferably, one would set the chunk-parameters to be a _big enough_ canvas, from which you can pull the smaller figure from within Illustrator or maybe even Plotgardener.

**Comment by teunbrand** [comment]
Hey Robin,

Because the `ggMarginal()` function returns a `gtable` class object, you should be able to manually set the widths/heights of the marginal plots. I've never used this function before, but the issue appears to be that they are 'null' units by defaults, which only makes sense in relation to other 'null' units in the same hierarchy of the plot. By setting an explicit panel size the 'null' unit that the panel usually takes to fit the window is gone and the marginal plots fill the leftover space.

``` r
library(ggh4x)
#> Loading required package: ggplot2
library(ggExtra)

p <- ggplot(mtcars, aes(x = mpg, y = disp)) +
  geom_point() +
  force_panelsizes(
    total_width = unit(42, "mm"),
    total_height = unit(42, "mm")
  )
p <- ggMarginal(p)

p$heights[1] <- unit(42 * 0.2, "mm")
p$widths[length(p$widths)] <- unit(42 * 0.2, "mm")
print(p)
```

![](https://i.imgur.com/V2WXHHk.png)

<sup>Created on 2023-08-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Good luck!
