### ISSUE TITLE
Incompatibility of facet_nested*() with ggbreak

### ISSUE THREAD

**Issue by rubisco57** [teunbrand/ggh4x#166]
I am very happy to use `ggh4x_0.2.8`, thank you for sharing this magic! Unfortunately, there is a compatibility issue of `facet_nested*() ` with broken axes as provided by `ggbreak_0.1.2 ` as can be seen from this example which throws `Error in vec_slice(): ! x must be a vector, not NULL.`:
```
new_iris <- transform(
  iris, 
  Nester = ifelse(Species == "setosa", "Short Leaves", "Long Leaves"),
  Nester2 = ifelse(Species == "setosa", "Short Leaves", "Long Leaves")
)

iris_plot <- ggplot(new_iris, aes(x = Nester, y = Sepal.Length)) +
  geom_point()
iris_plot

iris_plot +
  facet_nested_wrap(~ Nester2 + Species, nest_line = element_line(linetype = 2)) +
  scale_y_break(c(5,7)) +
  theme(strip.background = element_blank(),
        ggh4x.facet.nestline = element_line(colour = "blue"))
```
Maybe there is an easy fix to this and users could still benefit from the lighter strips separated by lines.

**Comment by teunbrand** [comment]
Thanks for the interest!

I'm afraid I'm not planning on maintaining some sort of compatibility with the ggbreak package.
Contrary to what name `scale_{x/y}_break()` implies, these do not actually produce scales.
Since guides need to interface with scales, there is no natural or elegant way that I can see to make ggh4x' guides work with ggbreak's "scales".

I'm going to close this for now as a 'won't fix'-issue, but if anyone sees an easy integration I can review a PR.

**Comment by teunbrand** [comment]
Sorry, I just realised you mean `facet_nested()` instead of `guide_axis_nested()`. For facets, see [previous commentary](https://github.com/teunbrand/ggh4x/issues/64).

**Comment by rubisco57** [comment]
Thank you, for your prompt reply and my apology for not finding the other article in the closed issues.
As a work around I am using an [interaction](https://teunbrand.github.io/ggh4x/articles/PositionGuides.html#nested-relations) which works with `ggbreak` with the minor caveat that the labeling is printed twice beneath both parts of the broken axis.
