### ISSUE TITLE
Remove line artefact on facet_nested plot

### ISSUE THREAD

**Issue by rubisco57** [teunbrand/ggh4x#170]
Great package, I am thankful for its existence!
Not sure whether this qualifies as a bug. I would like to get divider lines between two nested variables, however, setting the rectangle leaves some artifact:
<img width="471" alt="ggh4x_nestedline_problem" src="https://github.com/user-attachments/assets/830a6b39-f789-4aa9-b374-8cae2315ec62">
```
ggplot(mpg |> filter(manufacturer %in% c("chevrolet")) ) +
  geom_point(aes(x = year, y = displ)) +
  facet_nested(trans~ manufacturer + class,
               switch = "y",
               strip = strip_nested(
                background_x = list(element_part_rect(fill = "white", color = "black", side = "b"),
                                    element_rect(fill = "white", color = "white")),
                by_layer_x = TRUE
               )) +
  theme_bw() +
  theme(strip.placement = "outside")
```
Is there an easy fix to this?

**Comment by teunbrand** [comment]
Hi there thanks for the report!
I don't think this is a bug, but I appreciate you bringing this to my attention regardless.

What you call 'artifact' here are the good parts and the rest is too thin.
The issue occurs because the line is clipped by the white rectangles of the bottom layer.
You can restore well-displayed lines by making the fills transparent, i.e. use this for your `background_x` argument:

```r
list(
  element_part_rect(fill = NA, color = "red", side = "b"),
  element_rect(fill = NA, color = NA)
)
```

Alternatively, you can skip the whole tailoring of `strip_nested()` and use `nest_line = TRUE` to simply draw a line between different levels of the hierarchy.

As this issue is more of a quirk of the graphics system and not a true bug, I'll close this issue.

**Comment by rubisco57** [comment]
Wonderful! Thank you much for you insight, @teunbrand, and your immediate response. 
Good rest of the day!
