### ISSUE TITLE
Suppress computations

### ISSUE THREAD

**Issue by lorenzoFabbri** [teunbrand/ggh4x#46]
I am using the package for `stat_theodensity` but I would like to suppress the results of the different computations (e.g., `sd`). Is this possible? Thanks.

**Comment by teunbrand** [comment]
Yes, you can download an older version of the `fitdistrplus` package, or their [github version](https://github.com/aursiber/fitdistrplus). The current CRAN version includes a stray print statement that [has been removed since](https://github.com/aursiber/fitdistrplus/commit/1fd18a5770309b6bce24f997104591fa0ab77a38#diff-8c2574892063f995fdf756bce07f46c1a5193e54cd52837ed91e32008ccf41ac). The only option for me to do something about this is to wrap everything related to fitdistrplus in print suppressors, which seems a bit excessive for a bug that is already fixed on GH but not yet on CRAN. So for now, I won't be doing anything in ggh4x related to these print statements.
